### ISSUE TITLE
New Firmwares and switchers

### ISSUE THREAD

**Issue by rohanwright** [LibAtem/AtemProxy#4]
Hi, is this project still active and functional with newer switchers and firmware like the atem constelation hd 4me?
We have too many devices connected to our ATEM and it keeps crashing, looking for a solution.

**Comment by Julusian** [comment]
It should work fine with newer devices, this proxy is pretty naive in that it it is only looking for and blocking certain commands that we know will have issues running in this way, everything else will be forwarded untouched.

**Comment by Christoph111** [comment]
Hi, how to start the app correctly or better, how to configure it? It looks like its configured to be found in your user folder julus: /Users/julus/Projects/AtemProxy/LibAtem/LibAtem/Net/AtemClient.cs:line 48

here the terminal lines:
2023-06-19 21:57:48,242 [1] INFO  AtemProxy.Program - Starting
Unhandled exception. System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (22): Invalid argument
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at LibAtem.Net.AtemClient..ctor(String address, Boolean autoConnect) in /Users/julus/Projects/AtemProxy/LibAtem/LibAtem/Net/AtemClient.cs:line 48
   at AtemProxy.UpstreamConnection..ctor(String address) in /Users/julus/Projects/AtemProxy/AtemProxy/UpstreamConnection.cs:line 46
   at AtemProxy.Program.Main(String[] args) in /Users/julus/Projects/AtemProxy/AtemProxy/Program.cs:line 36
zsh: abort      /Applications/AtemProxy-v0.1.0-macos/AtemProxy --help

are you still working on this project? may be it would be great to have all files put into one or more subfolders and have a config file or something....
cheers

**Comment by Julusian** [comment]
It is expecting an ip address to be supplied as the argument when starting. It looks like it is trying to interpret the `--help` in your command as the ip address.

> are you still working on this project? may be it would be great to have all files put into one or more subfolders and have a config file or something....

The library this is using I am still working on when I have time and motivation, this proxy hasn't really seen much attention as I haven't had a need for it myself.

**Comment by Christoph111** [comment]
thanks, i managed to get it to work. It´s funny that not many people are involved here since it´s exactly what Skaarhoj sells for money (SKAARHOJ ATEM-TCP Link for 500$, or successor called bluepill with more features).
thanks for your work!

**Comment by AttitudeVision** [comment]
Jumping onto this thread as Christoph got this working in the last 6 months. 

I have compiled a windows distribution of the proxy (with difficulty) as I usually dev in js and I use the term Dev loosly. #

The exe runs correctly and connects to the Atem from what I can see, however the Atem software doesn't see a second constelation in MDNS discovery and adding the IP address of my local machine running the proxy doesn't do anything.

I feel like I am missing something incredibly simple

**Comment by imorrish** [comment]
I had built a Raspberry PI image that I ran for over 3 years. I'll try updating it.
https://ianmorrish.wordpress.com/2021/10/30/atemproxy-and-powershell-setup-on-raspberry-pi-4-2gb-model/
